# Generated by Django 3.1.7 on 2023-03-25 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20230325_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(default='owner.username', to=settings.AUTH_USER_MODEL),
        ),
    ]
