# Generated by Django 3.1.7 on 2023-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230325_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='owner',
        ),
    ]
