# Generated by Django 3.1.7 on 2023-03-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
