# Generated by Django 3.1.7 on 2023-03-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20230326_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='authors',
            new_name='author',
        ),
    ]
