# Generated by Django 3.1.7 on 2023-04-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
