# Generated by Django 3.1.7 on 2023-04-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20230404_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
