# Generated by Django 3.1.7 on 2023-04-04 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0046_remove_blog_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='readers', to=settings.AUTH_USER_MODEL, verbose_name='Читатели'),
        ),
    ]
