# Generated by Django 4.2 on 2023-04-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_blog_options_alter_blog_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
