# Generated by Django 4.2 on 2023-04-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
